  GNU nano 6.2                                       docker-compose.yml
version: "3.5"
services:
  pg_db:
    container_name: pg_db
    image: postgres:14.3-alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: oleg
      POSTGRES_DB: pgdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    network_mode: "host"
  mgf_test:
    container_name: mgf_test
    build: .
    volumes:
      - /var/log:/var/log
    network_mode: "host"
